# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo

  target 'demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
